apic_user: "CLUS-userXX" #edit this value using the shared details
apic_pass: "CLUS-userXX-123!" #edit this value using the shared details
apic_host: 198.19.202.66
apic_tenant: CLUS-userXX #edit this value using the shared details
