image: sabaroof/ciscolive2022:runner

before_script:
  - apt-get update -qy
  - ansible --version
  - export ANSIBLE_HOST_KEY_CHECKING=False

stages:
  - verify
  - predeploy
  - deploy

verify:
  stage: verify
  script:
    - ansible-playbook --inventory inventory.ini --syntax-check plays/task2-playbook.yml

predeploy:
  stage: predeploy
  script:
    - ansible --inventory inventory.ini all -m ping --connection httpapi
    - ansible-playbook --inventory inventory.ini plays/apic-snapshot-playbook.yml 
  
deploy:
  stage: deploy
  script:
    - ansible-playbook --inventory inventory.ini plays/task2-playbook.yml
  when: manual
